# Generated by Django 2.2.12 on 2020-10-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotchannel',
            name='api_key',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='iotchannel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
